__author__ = 'Mateusz Andrzejczuk (CiniCraft on GitHub)'
import getpass
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print "Likebot Developed By CiniCraft " + u"\u00A9" + " 2014 All Rights Reserved."
print ""
print ""
print "Before you begin you must log into web.stagram.com using your InstaGram account."
print "Likebot's authentication fails, you may need to re-log in to web.stagram.com."
print ""
username = raw_input("Enter your InstaGram username: ")
password = getpass.getpass('Password: ')

from likebot import login, like
import time

print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""

print "Authenticating..."
login(username, password)
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print "Success!"
time.sleep(2)
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print ""
print "========================================================================="
print "=                             MAIN MENU                                 ="
print "========================================================================="
print ""
print " ------------------------------------------------------------------------"
print "| Run likebot by entering the integer value of the options listed below: |"
print " ------------------------------------------------------------------------"
print ""
print "   [1] CUSTOM RUN  "
print "       Allows you to enter the number of hashtags to use, each hashtag name, "
print "       and the 'likes per hashtag' rate."
print ""
print ""
print "   [2] POWER LEVELING "
print "       This runs a massive list of hard coded hashtags and only likes two at a time."
print "       Power Leveling uses the top 1000 hashtags from March 27th 2014."
print ""
print ""



settings = raw_input("Enter 1 or 2 to begin: ")
settings = int(settings)

if settings == 1:
    numHashtags = raw_input("How many different hashtags would you like to use in this run? ")
    hashtags = []

    numRate = raw_input("Enter the desired likes per hashtag: ")
    numRate = int(numRate)
    i = int(numHashtags)

    while i > 0:
        tagitem = raw_input("Enter hashtag #" + str(i) + " :")
        hashtags.append(tagitem)
        i -= 1
        print hashtags
elif settings == 2:
    numRate = 2
    massiveHashTag_list = set(['InstamoodPhoto', 'FollowfollowPhoto', 'StylePhoto', 'LolPhoto', 'WebstagramPhoto', 'IphoneonlyPhoto', 'LlPhoto', 'PrettyPhoto', 'TweegramPhoto', 'MyPhoto', 'LikeforlikePhoto', 'NofilterPhoto', 'All_shotsPhoto', 'FamilyPhoto', 'LifePhoto', 'InstagoPhoto', 'HairPhoto', 'InstacoolPhoto', 'BoredPhoto', 'InstafollowPhoto', 'SunPhoto', 'EyesPhoto', 'CoolPhoto', 'LookPhoto', 'NicePhoto', 'FunnyPhoto', 'FfPhoto', 'FollowforfollowPhoto', 'GirlsPhoto', 'likesPhoto', 'ColorfulPhoto', 'PartyPhoto', 'ChristmasPhoto', 'InstacollagePhoto', 'SkyPhoto', 'NightPhoto', 'PinkPhoto', 'HotPhoto', 'FollowbackPhoto', 'ShoutoutPhoto', 'IphonesiaPhoto', 'ArtPhoto', 'RepostPhoto', 'MusicPhoto', 'BabyPhoto', 'BeachPhoto', 'ThrowbackPhoto', 'BeautyPhoto', 'NaturePhoto', 'BluePhoto', 'PhotoPhoto', 'ThrowbackthursdayPhoto', 'DayPhoto', 'BlackPhoto', 'HarrystylesPhoto', 'BoyfriendPhoto', 'MakeupPhoto', 'InstalovePhoto', 'AwesomePhoto', 'LoveitPhoto', 'DogPhoto', 'GoodPhoto', 'StatigramPhoto', 'BestPhoto', 'FitnessPhoto', 'OnedirectionPhoto', 'HomePhoto', 'NewPhoto', 'InstagramhubPhoto', 'RedPhoto', 'SweetPhoto', 'NiallhoranPhoto', 'InstapicPhoto', 'ShoesPhoto', 'LikesPhoto', 'IgdailyPhoto', 'TiredPhoto', 'YummyPhoto', 'APhoto', 'SchoolPhoto', 'BestfriendPhoto', 'ThePhoto', 'PicstitchPhoto', 'WhitePhoto', 'InstaphotoPhoto', 'CatPhoto', 'FriendPhoto', 'InPhoto', 'BirthdayPhoto', 'BoyPhoto', 'JjPhoto', 'ModelPhoto', 'LoveherPhoto', 'DoubletapPhoto', 'AndPhoto', 'YouPhoto', 'LouistomlinsonPhoto', 'SnowPhoto', 'WorkPhoto', 'InstagramersPhoto', 'OotdPhoto', 'YumPhoto', 'PerfectPhoto', 'GoodmorningPhoto', 'FoodpornPhoto', 'NikePhoto', 'CrazyPhoto', 'LikebackPhoto', 'SoPhoto', 'SisterPhoto', 'GoodtimesPhoto', 'GreenPhoto', 'TattooPhoto', 'ForeverPhoto', 'MorningPhoto', 'NailsPhoto', 'LoveyouPhoto', 'KikPhoto', 'ForPhoto', 'InstafoodPhoto', 'OldPhoto', 'HahaPhoto', 'HalloweenPhoto', 'TruthPhoto', 'SsPhoto', 'ToPhoto', 'WithPhoto', 'BestfriendsPhoto', 'FridayPhoto', 'BreakfastPhoto', 'WorkoutPhoto', 'AdorablePhoto', 'ShoppingPhoto', 'SeaPhoto', 'FacePhoto', 'HealthyPhoto', 'HeartPhoto', 'LovehimPhoto', 'BlessedPhoto', 'OutPhoto', 'IsPhoto', 'Jj_forumPhoto', 'YoloPhoto', 'ItPhoto', 'HerPhoto', 'BffPhoto', 'DressPhoto', 'CoffeePhoto', 'CakePhoto', 'JustinbieberPhoto', 'DinnerPhoto', 'TreePhoto', 'FreshPhoto', 'BoysPhoto', 'TodayPhoto', 'NoPhoto', 'BlondePhoto', 'OutfitPhoto', 'GoodnightPhoto', 'SaturdayPhoto', 'InstafashionPhoto', 'MemoriesPhoto', 'SundayPhoto', 'OfPhoto', 'CommentPhoto', 'GymPhoto', 'QuotePhoto', 'DrunkPhoto', 'FitPhoto', 'TeamfollowbackPhoto', 'ShoutoutsPhoto', 'PuppyPhoto', 'DeliciousPhoto', 'ChocolatePhoto', 'WinterPhoto', 'TruePhoto', 'Photo', 'CloudsPhoto', 'BrunettePhoto', 'DesignPhoto', 'WeddingPhoto', 'YellowPhoto', 'FlowersPhoto', 'BeerPhoto', 'LovelyPhoto', 'KissPhoto', 'NycPhoto', 'TumblrPhoto', 'CousinPhoto', 'PicturePhoto', 'KittyPhoto', 'WeekendPhoto', 'HarryPhoto', 'AsianPhoto', 'ZaynmalikPhoto', 'CutiePhoto', 'TimePhoto', 'LmaoPhoto', 'LittlePhoto', 'BrotherPhoto', 'PicPhoto', 'KuwaitPhoto', 'LaPhoto', 'LivePhoto', 'CityPhoto', 'HolidayPhoto', 'LondonPhoto', 'LightPhoto', 'GorgeousPhoto', 'InspirationPhoto', 'LovethemPhoto', 'OrangePhoto', 'RelaxPhoto', 'dPhoto', 'ExcitedPhoto', 'SleepPhoto', 'SunshinePhoto', 'FallPhoto', 'LiampaynePhoto', 'BlackandwhitePhoto', 'UsaPhoto', 'OnPhoto', 'DisneyPhoto', 'MotivationPhoto', 'LouisPhoto', 'HappinessPhoto', 'SpringPhoto', 'CatsPhoto', 'ThisPhoto', 'InstahubPhoto', 'PeacePhoto', 'ColdPhoto', 'WaterPhoto', 'ItalyPhoto', 'KikmePhoto', 'SistersPhoto', 'NewyorkPhoto', 'TreesPhoto', 'SunnyPhoto', 'Photo', 'DrawingPhoto', 'ZaynPhoto', 'FriendshipPhoto', 'TravelPhoto', 'ViewPhoto', 'IloveyouPhoto', 'LiamPhoto', 'GoldPhoto', 'RainPhoto', 'InlovePhoto', 'ChillinPhoto', 'LunchPhoto', 'LaughPhoto', 'UpPhoto', 'MoviePhoto', 'DirectionerPhoto', 'ParisPhoto', 'JapanPhoto', 'AnimalPhoto', 'YoungPhoto', 'DancePhoto', 'ChillPhoto', 'CarPhoto', 'CouplePhoto', 'PoolPhoto', 'HeelsPhoto', 'DrinksPhoto', 'PleasePhoto', 'MiamiPhoto', 'WeirdPhoto', 'ThailandPhoto]'])
    hashtags = list(massiveHashTag_list)
    hashtags.sort()
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print ""
    print "Would you like to start from a specific index of this massive hashtag list?"
    print "(there are " + str(len(hashtags)) + " hashtags in this list, start from 0 to " + str(len(hashtags)) + ")"
    print ""
    yn = raw_input("y or n :")
    if yn == "y" or "Y" or "yes" or "Yes":
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        print ""
        start = raw_input("Start from index: ")
        hashtags = hashtags[int(start):len(hashtags)]
# CiniCraft

like(hashtags, numRate)